option(LINGMO_ENABLE_SANITIZERS "Enable sanitizers" OFF)
if(LINGMO_ENABLE_SANITIZERS AND NOT MSVC)
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag(-fsanitize=address HAS_ASAN)
    if(HAS_ASAN)
        add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address)
    endif()
endif()
